### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by BootstrapB** [kenders2000/WindNoiseDetection#11]
This is my first time trying to compile something and I'm not sure if I'm doing it right. I'm using ubuntu and I navigated to the location of the Makfile and wrote make in the command line. It appeared to compile and I didn't get any errors but when I run windDet.exe -i test/iphone1.wav -o test/iphone1.txt -j test/iphone1.json -t 1 -g 1 -f 43 -w 25 -v 0 it tells me windDet.exe: command not found. After compiling, a windDet file was created but it doesn't have a .exe or any extension. Any help would be appreciated.

**Comment by kenders2000** [comment]
Running executables in Linux is different to windows. You should replace windDet.exe with .windDet
Hope that helps

Paul

**Comment by BootstrapB** [comment]
Ok thanks, I probably should have figured that out.
