### ISSUE TITLE
Terminal output

### ISSUE THREAD

**Issue by kimadactyl** [kenders2000/WindNoiseDetection#2]
I'm having some issues detecting if the processor has run correctly. Would it be possible to have the binary output an exit status on stdout so I can monitor it within the webapp? Convention is that exit status 0 for success and 1 for failure. 

http://www.gnu.org/software/libc/manual/html_node/Exit-Status.html

**Comment by kimadactyl** [comment]
I'm still getting the old terminal output. Not sure I described this correctly. What I mean is that the program should not output all the stuff it does now but rather an exit code. It's because I need to be able to go:

```
status = `./windDet -i /home/kim/NoiseEater/public/audio/3/iphone1.wav -o /home/kim/NoiseEater/public/audio/3/output -j /home/kim/NoiseEater/public/audio/3/data.json`
```

And then compare the output of status so I can see if it completed successfully or not in a machine-friendly way.

Make sense? Apologies if you did this and I'm getting the wrong end of the stick!

**Comment by kenders2000** [comment]
Hi,

So currently I’m printing out a bunch of printf statements as it goes through the program as a kind of status of the progress of the thing. 

do you need me basically remove these statements and just print out a 0 1 at the end depending on the success of the program?

I’ve not written much like this before so I don’t really know the conventions!

BTW I nearly have the distortion detection working, the code works just a bit of tidying up of outputs.

Regards

Paul

**Comment by kimadactyl** [comment]
I don't think it's a terminal output, it's the exit statement of the program. Well behaved stuff shouldn't output anything I think?

This seems to be the thing? http://www.cplusplus.com/reference/cstdlib/exit/

**Comment by kenders2000** [comment]
Ok so now there is now a new branch with no terminal outputs, and just (hopefully) returns the correct number on success (0) or failure (1), unless it crashes of course then there is nothing!

Let me know if that does what you expect if it not let me know, im learning as I go here!

Cheers

Paul
